[2024-06-19T03:02:47.989+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T03:02:50.091+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-06-19T03:02:29.032343+00:00 [queued]>
[2024-06-19T03:02:50.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-06-19T03:02:29.032343+00:00 [queued]>
[2024-06-19T03:02:50.233+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T03:02:51.035+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-06-19 03:02:29.032343+00:00
[2024-06-19T03:02:51.054+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-06-19T03:02:29.032343+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpsl0_gmtv']
[2024-06-19T03:02:51.103+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask extract_data_from_wikipedia
[2024-06-19T03:02:51.199+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8654) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-19T03:02:51.200+0000] {standard_task_runner.py:63} INFO - Started process 8666 to run task
[2024-06-19T03:02:52.603+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-06-19T03:02:29.032343+00:00 [running]> on host 94e1e91ab96d
[2024-06-19T03:02:54.820+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ayush Goswami' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T03:02:29.032343+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T03:02:29.032343+00:00'
[2024-06-19T03:02:54.915+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T03:03:17.268+0000] {logging_mixin.py:188} INFO - Getting wiki page https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2024-06-19T03:03:19.550+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T03:03:19.551+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 29, in extract_wikipedia_data
    tds=rows[i].findall('td')
        ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
[2024-06-19T03:03:19.592+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, run_id=manual__2024-06-19T03:02:29.032343+00:00, execution_date=20240619T030229, start_date=20240619T030250, end_date=20240619T030319
[2024-06-19T03:03:19.659+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task extract_data_from_wikipedia ('NoneType' object is not callable; 8666)
[2024-06-19T03:03:19.699+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T03:03:19.733+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T03:03:19.787+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
