[2024-06-07T08:13:14.005+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: example_bash_operator.this_will_skip manual__2024-06-07T08:06:01+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
