[2024-06-19T02:22:12.277+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T02:22:13.865+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-06-19T02:22:02.089246+00:00 [queued]>
[2024-06-19T02:22:14.014+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-06-19T02:22:02.089246+00:00 [queued]>
[2024-06-19T02:22:14.014+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T02:22:14.400+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-06-19 02:22:02.089246+00:00
[2024-06-19T02:22:14.415+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-06-19T02:22:02.089246+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmp3loy1ci1']
[2024-06-19T02:22:14.422+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask extract_data_from_wikipedia
[2024-06-19T02:22:14.430+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7357) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-19T02:22:14.432+0000] {standard_task_runner.py:63} INFO - Started process 7363 to run task
[2024-06-19T02:22:15.031+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-06-19T02:22:02.089246+00:00 [running]> on host 94e1e91ab96d
[2024-06-19T02:22:16.314+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ayush Goswami' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T02:22:02.089246+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T02:22:02.089246+00:00'
[2024-06-19T02:22:16.332+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T02:22:16.684+0000] {logging_mixin.py:188} INFO - Getting wiki page https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2024-06-19T02:22:31.615+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T02:22:31.616+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 23, in extract_wikipedia_data
    rows=get_wikipedia_data(html)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 14, in get_wikipedia_data
    table=soup.find_all("table",{'class':'wikitable sortable sticky-header jquery-tablesorter'})[0]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-06-19T02:22:31.661+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, run_id=manual__2024-06-19T02:22:02.089246+00:00, execution_date=20240619T022202, start_date=20240619T022213, end_date=20240619T022231
[2024-06-19T02:22:31.748+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task extract_data_from_wikipedia (list index out of range; 7363)
[2024-06-19T02:22:31.818+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T02:22:31.853+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T02:22:31.889+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
