[2024-06-19T07:23:38.832+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T07:23:39.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-19T07:23:10.200676+00:00 [queued]>
[2024-06-19T07:23:39.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-19T07:23:10.200676+00:00 [queued]>
[2024-06-19T07:23:39.660+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T07:23:40.245+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-06-19 07:23:10.200676+00:00
[2024-06-19T07:23:40.266+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-06-19T07:23:10.200676+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmptf_6odl8']
[2024-06-19T07:23:40.271+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask transform_wikipedia_data
[2024-06-19T07:23:40.282+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=903) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-19T07:23:40.284+0000] {standard_task_runner.py:63} INFO - Started process 922 to run task
[2024-06-19T07:23:40.456+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-19T07:23:10.200676+00:00 [running]> on host dd278de8866b
[2024-06-19T07:23:41.255+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ayush Goswami' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T07:23:10.200676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T07:23:10.200676+00:00'
[2024-06-19T07:23:41.257+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T07:23:42.354+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T07:23:42.354+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 66, in transform_wikipedia_data
    data=kwargs['ti'].xcom_pull(keys='rows',task_ids='extract_data_from_wikipedia')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'keys'
[2024-06-19T07:23:42.417+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=transform_wikipedia_data, run_id=manual__2024-06-19T07:23:10.200676+00:00, execution_date=20240619T072310, start_date=20240619T072339, end_date=20240619T072342
[2024-06-19T07:23:42.544+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task transform_wikipedia_data (TaskInstance.xcom_pull() got an unexpected keyword argument 'keys'; 922)
[2024-06-19T07:23:42.593+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T07:23:42.670+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T07:23:42.714+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
